# fly.toml app configuration file generated for program-lsniacastrefa
# Updated manually for FastAPI + Uvicorn

app = 'program-lsniacastrefa'
primary_region = 'fra'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
